[[chapter10]]
== Fast non-linear operations
=== Introduction
In the fast nonlinear instructions vs2 store the fixed-point value in Q32.n format，vs1 store the point position n of the fix point format, n belongs to [0, 31]. vd stores the fix point position n of nonlinear function's output by exponent calculation instruction and it's mantissa value in Q32.n format by mantissa calculation instruction. +

The segmentation of the nonlinear function is represented by five parameters A, B, S, E and T. A represents the slope of the straight line, B represents the bias of the straight line, S represents the mantissa value of the starting position of the straight line on X-axis, E is the exponent values in the nonlinear function calculation procedure, T is the nonlinear function type. The vector nonlinear function needs to perform a segmented search and linear fitting for each element of the vector.+

=== Vector nonlinear parameter register
The segmentation information of the nonlinear function is stored through the parameter configuration registers vnlcr0 and vnlcr1. The length of vnlcr0 and vnlcr1 is 1024bits. This register is configured through the vlnlp instruction. +

- *vnlpr0 1024bits (vector non-linear paramter register 0)*
[cols="2*", options="header"]
|================================
|    R_NL_A[16]   |   R_NL_B[16]
|================================

- *vnlpr1 1024bits (vector non-linear paramter register 1)*
[cols="2*", options="header"]
|================================
| R_NL_SEG_EXP[16] | R_NL_SEG[16]
|================================

R_NL_SEG[16]: 16 nonlinear function segment fix points registers +
R_NL_SEG_EXP[16]: R_NL_SEG_EXP(0) stores the fix point position of R_NL_A[16] and R_NL_B[16]; R_NL_SEG_EXP(1) stores the fix point position of fitting result; R_NL_SEG_EXP(2) stores the fix point position of R_NL_SEG[16]; +
R_NL_A[16]: 16 nonlinear function segement slope registers +
R_NL_B[16]: 16 nonlinear function segement offset registers +

=== Instructions
==== vlnlp(vector load nonlinear parameter)
. *Grammar*
+
vlnlp.v vnlpr, vs2 +

. *Purpose*
+
Moving nonlinear function parameter configuration from vector register to nonlinear function parameter registers vnlpr0 and vnlpr1

. *Description*
+
Moving configuration from vector register vs2 to vnlpr0 and vnlpr1, 2048bits in total. LMUL is set to 2 contantly.

. *Operation*
+
----
vnlpr.l = VR[n]       // .l means low 1024bits in vnlpr
vnlpr.h = VR[n+1];    // .h means high 1024bits in vnlpr
----

==== vnle(vector non-linear exponent calculation instruction)
. *Grammar*
+
vnle.vv vd, vs2, vs1, vm +
vnle.vs vd, vs2, vs1, vm +

. *Purpose*
+
Computes the exponential part of the output value of a nonlinear function of an input vector.

. *Description*
+
vs2 stores the fixed-point value, vs1 or vs1[0] stores the fixed-point value n. According to the function type configured in the nonlinear control register, the corresponding exponential result E is calculated, and the result is placed in vd.

. *Operation*
+
----
VV version
x[i], E[i] = norm(R_NL_TYPE, vs2[j][i], vs1[j][i])
x[i], s[i], E[i] = preProc(R_NL_TYPE, x[i], E[i])
(vd[j][i], E[i]) = expAdjust(R_NL_TYPE, E[i])

VS version
x[i], E[i] = norm(R_NL_TYPE, vs2[j][i], vs1[0][0])
x[i], s[i], E[i] = preProc(R_NL_TYPE, x[i], E[i])
(vd[j][i], E[i]) = expAdjust(R_NL_TYPE, E[i])
----

==== vnlm(vector non-linear mantissa calculation instruction)
. *Grammar*
+
vnlm.vv vd, vs2, vs1, vm +
vnlm.vs vd, vs2, vs1, vm +

. *Purpose*
+
Computes the linear portion of the output of a nonlinear function of the input vector.

. *Description*
+
vs2 stores the fixed-point value, vs1 or vs1[0] stores the fixed-point value n. According to the function type configured in the nonlinear control register and the segmented parameter configuration, the segmented nonlinear result is calculated. Finally, the results are put into vd after fix point format conversion. 

. *Operation*
+
----
VV version
x[i], E[i] = norm(R_NL_TYPE, vs2[j][i], vs1[j][i])
x[i], s[i], E[i] = preProc(R_NL_TYPE, R_NL_SEG_EXP, x[i], E[i])
segIdx[i] = findSeg(x[i], R_NL_SEG)
If (segIdx[i] is valid)
{ 
  tmp = A[segIdx[i]] * x[i]; //2SEW = SEW * SEW
  tmp = clip_low_SEW(alg_round_shift_right(tmp, R_NL_SEG_EXP[2])) + B[segIdx[i]]; //SEW = SEW + SEW
  if R_NL_SEG_EXP[1] >= R_NL_SEG_EXP[0]
    tmp <<= R_NL_SEG_EXP[1] - R_NL_SEG_EXP[0]
  else
    tmp >>= R_NL_SEG_EXP[0] - R_NL_SEG_EXP[1]
  e[i], E[i] = expAdjust(R_NL_TYPE, E[i]);
  vd[j][i] = postProc(R_NL_TYPE, tmp, s[i], E[i]);
}

VS version
x[i], E[i] = norm(R_NL_TYPE, vs2[j][i], vs1[0][0])
x[i], s[i], E[i] = preProc(R_NL_TYPE, x[i], E[i])
segIdx[i] = findSeg(x[i], R_NL_SEG)
If (segIdx[i] is valid)
{ 
  tmp = A[segIdx[i]] * x[i]; //2SEW = SEW * SEW
  tmp = clip_low_SEW(alg_round_shift_right(tmp, R_NL_SEG_EXP[2])) + B[segIdx[i]]; //SEW = SEW + SEW
  if R_NL_SEG_EXP[1] >= R_NL_SEG_EXP[0]
    tmp <<= R_NL_SEG_EXP[1] - R_NL_SEG_EXP[0]
  else
    tmp >>= R_NL_SEG_EXP[0] - R_NL_SEG_EXP[1]
  e[i], E[i] = expAdjust(R_NL_TYPE, E[i]);
  vd[j][i] = postProc(R_NL_TYPE, tmp, s[i], E[i]);
}
----

*Note*: the definition of the basic operations for norm/preProc/findSeg/postProc/expAdjust are defined at chapter 12.
