[[chapter9]]
== Inter-element operation instructions

=== vperm(vector permutation)
. *Grammar*
+
vperm.vi vd, vs2, uimm +

. *Purpose*
+
According to the element sorting mode predefined by the customer, some elements are taken out from the elements of the source vector register, the elements are reordered according to a certain defined sorting mode and output to the destination vector register.

. *Description*
+
The original data is stored in vs2. uimm selects a predefined sorting mode and takes out elements from vs2 according to the new element sorting mode and places them in new positions in vd. The values ​​at the X index position are filled with 0. The pattern index starts counting from 0.
+
Patterns e.g.
+
P0：012...31 -> 012X345X678X......X 21 22 23X +
P1: 012345 -> 012345XX......X X 18 19 20 21 22 23 X X +
P2: 01 -> 0101010101010101XXXXXXXXXXXXXXXX +
P3: 01234567 -> 0011223344556677XXXXXXXXXXXXXXXX +
P4: 012 -> 012012012012XXXXXXXXXXXXXXXXXXXX +
P5: 0123 -> 000111222333XXXXXXXXXXXXXXXXXXXX +
P6: 0123 -> 0123012301230123XXXXXXXXXXXXXXXX +
P7: 0123 -> 0000111122223333XXXXXXXXXXXXXXXX +
P8: 0123 ... 31 -> 31 .... 3210 +
+
. *Operation*
+
----
vd[i] = vs2[PATTEN[uimm][i]]
----

=== vfsl(vector funnel shift left)
. *Grammar*
+
vfsl.vv vd, vs2, vs1 +

. *Purpose*
+
The elements of two vector registers are funnel shifted left.

. *Description*
+
combine vs2 and vs1 to form a new vector vr_temp with twice the length from left to right. All elements in vr_tmp are sequentially shifted left by fsht bits, left most 'fsht' elements are shifted out and discarded. Finally, the left half of vr_tp are output to vd. Only LMUL=1 is supported.

. *Operation*
+
----
vd = {vs2[(31- fsft) ... 0], vs1[31 ... (31 - fsft + 1)]}
----


=== vfsr(vector funnel shift right)
. *Grammar*
+
vfsr.vv vd, vs2, vs1 +

. *Purpose*
+
The elements of two vector registers are funnel shifted right.

. *Description*
+
combine vs2 and vs1 to form a new vector vr_temp with twice the length from left to right. All elements in vr_tmp are sequentially shifted right by 'fsht' elements, right most 'fsht' elements are shifted out and discarded. Finally, the right half of vr_tmp are output to vd. Only LMUL=1 is supported.

. *Operation*
+
----
vd = {vs2[(fsft - 1) ... 0], vs1[31 ... fsft]}
----

