[[chapter2]]
== Registers

. *VCSR* (Vector Control and Status Register)
+
Add new fields to the vector control and status register (vcsr) to control the fixed-point multiplication with shift, fixed-point accumulation with shift, and funnel shift related instructions.

* _mulsft_ (multiply shift) controls the right shift operation after the multiplier operation. The right shift operation is round shift, and the round mode is controlled by vxrm. 

* _accsft_ (accumulated shift) controls the right shift operation of the accumulation operation. The shift operation is round shift, and the round mode is controlled by vxrm. 

* _fsft_ configures the shift length of the funnel shift, so that the operation can realize flexible funnel shift function without increasing the source operand.
+
.VCSR bit fields table
[cols="3*", options="header"]
|====================================
| Bitfield  | Name  | Description          
| 31:18 | rsv          | reserve        
| 17:13 | fsft         | elements num. of funnel shift   
| 12:8  | accsft[12:8] | accumulation shift，0 ~ 31 
| 7:3   | mulsft[7:3]  | multiply shift，0 ~ 31 
| 2:1   | vxrm[1:0]    | rounding mode  
| 0     | vxsat        |             
|====================================


. *VNLCR* (Vector non-linear Control Register)
+
This register is used to configure the function type and segmentation information of the nonlinear function. The register width is 32 bits, configured through the Zicsr extended instruction, address _0x00E_.

* _FuncId_ configures the type of the current nonlinear function; 

* _SegGruCnt_ configures the number of segments of the nonlinear function. The maximum number of segments of the nonlinear function is 16. 
+
.VNLCR bit fields table
[cols="3*", options="header"]
|==============================
| Bitfield  | Name  | Description       
| 31:16 | SegGruCnt | segments num. of non-linear function. 0：reciprocal; 1: square root; 2: reciprocal of square root; 3: log2; 4: arctan
| 15:0  | funcId    | non-linear function ID. 0: 4 segments; 1：8 segments; 2：12 segments; 3：16 segments
|==============================

