[[chapter7]]
==  Dynamic scaling Reduced operation

=== vdsredsum(vector dynamic scaling reduced sum)
. *Grammar*
+
vdsredsum.v vd, vs2, vm +

. *Purpose*
+
Each element in the vector register is accumulated and then shifted to the right dynamically, and the output width remains unchanged.

. *Description*
+
The elements in vs2 are accumulated and the accumulated value is dynamically shifted to the right by round arithmetic and then the low SEW bit is intercepted and output to vd[0].

. *Operation*
+
----
Tmp = 0；
For each i in vs2 
    Tmp += v0.b[i] == 0 ? 0 : vs2[i]  // 2SEW = SEW

vd[0] = clip_low_2SEW_SEW(alg_round_shift_right(tmp, accsft)) // SEW = 2SEW
----

=== vdsredsumn(vector dynamic scaling reduced sum for each n element)
. *Grammar*
+
vdsredsumn.vs vd, vs2, rs1 +
vdsredsumn.vi vd, vs2, uimm +

. *Purpose*
+
Every n elements in the vector register are accumulated and then round shifted before output, where n is the power of an integer of 2.

. *Description*
+
Every 2^rs1 elements in vs2 are accumulated and then do algorithm round right shift before output to vd. if vl is not the interger multiple of 2^rs1, the real processing length is 2^rs1 * ceiling(vl/2^rs1). The valid value in rs1 is integer between [1, log2(VLEN/SEW)).

. *Operation*
+
----
VS version
n = 2^rs1 * ceiling(vl/2^rs1)
for (i = 0; i < VLEN/32/n; i++)
{
  start = i * n
  end = i * n + n - 1
  temp  = sum(vs2[start ... end])  //2SEW = SEW
  vd[i] = clip_low_2SEW_SEW(alg_round_shift_right(temp, accsft)) //SEW = 2SEW
}

VI version
n = 2^uimm * ceiling(vl/2^uimm)
for (i = 0; i < VLEN/32/n; i++)
{
  start = i * n
  end = i * n + n - 1
  temp  = sum(vs2[start ... end]) //2SEW = SEW
  vd[i] = clip_low_2SEW_SEW(alg_round_shift_right(temp, accsft)) //SEW = 2SEW
}
----


=== vredmaxi(vector reduced max with index)
. *Grammar*
+
vredmaxi.vv vd, vs2, vs1, vm +

. *Purpose*
+
Find the maximum value in the vector register and its corresponding index value and output it to the first and second elements in the target register.

. *Description*
+
vs2 saves the input value, vs1 saves the index value corresponding to each input value, finds the maximum value in vs2 and writes it into vd[0], and its corresponding index value is written into vd[1]. If the maximum value appears in multiple locations, output The first maximum value searched from low element to high element into vd. Default max value is the same as RVV 1.0, default index value is 0.

. *Operation*
+
----
vd[0] = max[vs2]; 
i = max_i[vs2]; // First maximum value searched from lowest element
vd[1] = vs1[i];
----

=== vredmini(vector reduced min with index)
. *Grammar*
+
vredmini.vv vd, vs2, vs1, vm +

. *Purpose*
+
Find the minimum value in the vector register and its corresponding index value and output it to the first and second elements in the target register.

. *Description*
+
vs2 saves the input value, vs1 saves the index value corresponding to each input value, finds the minimum value in vs2 and writes it into vd[0], and its corresponding index value is written into vd[1]. If the minimum value appears in multiple locations, output The first minimum value searched from low element to high element into vd. Default min value is the same as RVV 1.0, default index value is 0.

. *Operation*
+
----
vd[0] = min[vs2];
i = min_i[vs2]; //First minimum value searched from lowest element
vd[1] = vs1[i];
----

