[[chapter2]]
== Registers

. VCSR Register

Add new fields to the vector control and status register (vcsr) to control the fixed-point multiplication with shift, fixed-point accumulation with shift, and funnel shift related instructions. 

* _mulsft_ (multiply shift) controls the right shift operation after the multiplier operation. The right shift operation is round shift, and the round mode is controlled by vxrm. 

* _accsft_ (accumulated shift) controls the right shift operation of the accumulation operation. The shift operation is round shift, and the round mode is controlled by vxrm. 

* _fsft_ configures the shift length of the funnel shift, so that the operation can realize flexible funnel shift function without increasing the source operand.

.VCSR bit fields table
[cols="^1,^1,^1,^1,^3,^3",stripes=even,options="header"]
|===
4+|Letters _and_ bits {set:cellbgcolor:green} 2+|A much longer area
|L|R|W|X|Quarter 1|Quarter 2
|{set:cellbgcolor:!} 0|0|0|0 2+|Rows alternate colors
|0|0|0|1|Thing 1|Thing 2
|1|0|0|0|Thing 3|Thing 4
|1|1|1|1 2+|Span Thing 1 and 2
|===


