[[chapter1]]
== Basic operations definition

. *Basic Operations*
+
- int8: 8 bit signed char 
- int16: 16 bit signed half word
- int32: 32 bit word
- sc16: signed complex with 16bits image and 16bits real part, real part in low 16bit. e.g. 0xFFFD0005, image = -3, real = 5
- get_e: Get the exponent part in the Complex Packed Float-point format(CPF), 4bit exponent at highest bits, following 6bits image part, and real part at the lowest 6bits. e.g 0x3F45 = 0b 0011 1111 0100 0101, the exponent part is at highest bits, get_e(0x3F45) = 0b'0011' 
- get_i: Get the imaginary part in the Complex Packed Float-point format(CPF), 4bit exponent at highest bits, following 6bits image part, and real part at the lowest 6bits. e.g 0x3F45 = 0b 0011 1111 0100 0101, the image part is the 6 bits after exponent bits, get_i(0x3F45) = 0b'111101'
- get_r: Get the real part in the complex compressed format(CPF), 4bit exponent at highest bits, following 6bits image part, and real part at the lowest 6bits. e.g 0x3F45 = 0b 0011 1111 0100 0101, the real part is the lowest 6 bits, get_r(0x3F45) = 0b'000101'
- zp16: Add 0 to 16 bits at lowest bits. e.g.zp16(0b'111101') = 0b'1111010000000000'
- zp32: Add 0 to 32 bits at lowest bits. e.g.zp32(0b'111101') = 0b'11110100000000000000000000000000'
- sx16: sign extension to 16 bits. e.g. sx16(0b'111101') = 0xFFFD.
- sx32: sign extension to 32 bits. e.g. sx16(0b'111101') = 0xFFFFFFFD.
- min: Find the minimum value from a vector register from right to left. the right element have the higher priority to be the minimum value if there are multiple element equal to minimum value.
- max: Find the maximum value from a vector register from right to left. the right element have the higher priority to be the maximum value if there are multiple element equal to maximum value.
- min_i: Find the element index in the vector register where the minimum value is located.
- max_i: Find the element index in the vector register where the maximum value is located.
- lsb: The number of leading sign bit number minus 1. e.g. lsb( 0b'00010010') = 2, lsb( 0b'11111101') = 5.
- cpf_pack: Put e, i and r into the compressed complex format according to the complex compressed format. e.g. cpf(e=0x3, i=0xFFFD, r=0x5) = 0x3F45
- vcpack: extract the high 16 bits of 32-bit real numbers and 32-bit imaginary numbers in rounding mode to form a complex number in SC16 format. e.g i = 0x00058000, r = 0x00038000, vcpack(0x00058000, 0x00038000) = 0x00060004
- sum: sum
- conj: Convert a complex to it's conjugate complex.
- alg_round_shift_right: Arithmetic right shift with vxrm mode rounding, e.g. vxrm=rnu, alg_round_shift_right(0x0005, 1) = 0x3
- alg_shift_left: Arithmetic left shift with Saturate. 
- alg_shift_right: Arithmetic right shift without rounding. e.g. alg_shift_right(0x0005, 1) = 0x2
- shift_left: Logical left shift.
- clip_low_SEW:  Saturate and clip the lowest SEW width bit number. e.g. SEW=32bit, clip_low_SEW(0x0050000000) = 0x50000000; clip_low_SEW(0x0080000000) = 0x7fffffff;
- round_clip_high_SEW: Saturate clip the high SEW width bit number with vxrm mode rounding. e.g. SEW=32bit, round_clip_high_SEW(0x0050000381) = 0x00500004, round_clip_high_SEW(0x7fffffff80) = 0x7fffffff
- MIN_SEW: The minimum value of the signed number corresponding to the element of SEW bit width
- MAX_SEW: The maximum value of the signed number corresponding to the element of SEW bit width
- ACCREG[i]: The i-th accumulation register inside the MAC ALU, 80 bits, 32 elements in total
- MULSFTREG[i]: The i-th multiply shift register inside the MAC ALU, 5bits/element, 8*32 elements in total

