[[chapter10]]
== Fast non-linear operations
=== Introduction
In the fast nonlinear instructions vs2 store the fixed-point value in Q32.n format，vs1 store the fix point value n of the fix point format, n belongs to [0, 31]. vd stores the scaling shift value or the mantissa value of the fix point nonlinear output. +

The segmentation of the nonlinear function is represented by five parameters A, B, S, SE and T. A represents the slope of the straight line, B represents the bias of the straight line, S represents the mantissa value of the starting position of the straight line on X-axis, SE is the exponent value value of the starting position of the straight line on X-axis, T is the nonlinear function type. +

4 segments form a segment group. The vector nonlinear function needs to perform a segmented search for each element in the vector. If each element is searched for all segments at the same time, it consumes too much hardware resources, and the number of segments can change in scenarios with different accuracy requirements.
In order to reduce hardware resources and make linear segmentation settings more flexible, linear segments need to be grouped into K segment groups, each group has 4 segments. Each instruction only scans one segment group at a time. More accuracy needs more segment groups, with more segment groups it needs to call the instruction multiple times, each call only scans one of the segment group. +

The starting index of the segment group is random. Each time when vnlm instruction is called, the segment group index is incremented by one. After calling K times, the entire segment range is covered.

=== Vector nonlinear parameter register
The segmentation information of the nonlinear function is stored through the parameter configuration registers vnlcr0 and vnlcr1. The length of vnlcr0 and vnlcr1 is 1024bits. This register is configured through the vlnlp instruction. +

- *vnlpr0 1024bits (vector non-linear paramter register 0)*
[cols="2*", options="header"]
|========================
| R_NL_A[16] | R_NL_B[16]
|========================

- *vnlpr1 1024bits (vector non-linear paramter register 1)*
[cols="2*", options="header"]
|================================
| R_NL_SEG_EXP[16] | R_NL_SEG[16]
|================================

R_NL_SEG[16]: 16 nonlinear function segment points registers +
R_NL_SEG_EXP[16]: 16 nonlinear function segment points exponent registers (required for some nonlinear functions) +
R_NL_A[16]: 16 nonlinear function segement slope registers +
R_NL_B[16]: 16 nonlinear function segement offset registers +

=== Instructions
==== vlnlp(vector load nonlinear parameter)
. *Grammar*
+
vlnlp.s rs1 +

. *Purpose*
+
Load nonlinear function parameter configuration from vector memory to nonlinear function parameter registers vnlpr0 and vnlpr1

. *Description*
+
Load configuration from vector memory address rs1 to vnlpr0 and vnlpr1, a total of 2048bits.

. *Operation*
+
----
vnlpr0 = *rs1;
vnlpr1 = *(rs1 + 128);
----

==== vnle(vector non-linear exponent calculation instruction)
. *Grammar*
+
vnle.vv vd, vs2, vs1, vm +
vnle.vs vd, vs2, vs1, vm +

. *Purpose*
+
Computes the exponential part of the output value of a nonlinear function of an input vector.

. *Description*
+
vs2 stores the fixed-point value, vs1 or vs1[0] stores the fixed-point value n. According to the function type configured in the nonlinear control register, the corresponding exponential result E is calculated, and the result is placed in vd.

. *Operation*
+
----
VV version
x[i], E[i] = NORM(R_NL_TYPE, vs2[i], vs1[i])
x[i], s[i], E[i] = preproc(R_NL_TYPE, x[i], E[i])
vd[i] = ExpAdjust(R_NL_TYPE, E[i])

VS version
x[i], E[i] = NORM(R_NL_TYPE, vs2[i], vs1[0])
x[i], s[i], E[i] = preproc(R_NL_TYPE, x[i], E[i])
vd[i] = ExpAdjust(R_NL_TYPE, E[i])
----

==== vnlm(vector non-linear mantissa calculation instruction)
. *Grammar*
+
vnlm.vv vd, vs2, vs1, vm +
vnlm.vs vd, vs2, vs1, vm +

. *Purpose*
+
Computes the linear portion of the output of a nonlinear function of the input vector.

. *Description*
+
vs2 stores the fixed-point value, vs1 or vs1[0] stores the fixed-point value n. According to the function type configured in the nonlinear control register and the segmented parameter configuration, the segmented nonlinear result is calculated. Finally, the results are put into vd after fix point format conversion.

. *Operation*
+
----
VV version
x[i], E[i] = NORM(R_NL_TYPE, vs2[i], vs1[i])
x[i], s[i], E[i] = preproc(R_NL_TYPE, x[i], E[i])
segIdx[i] = findSeg(x[i], R_SEG[N])  // N is segment group ID
If (segIdx[i] is valid)
{ 
tmp = alg_round_shift_right((A[segIdx[i]] * x[i]), n) + B[segIdx[i]];
Vd[i] = postproc(R_NL_TYPE, tmp)
}
N =(N+1) mod K;  //K is the max segments group number

VS version
x[i], E[i] = NORM(R_NL_TYPE, vs2[i], vs1[0])
x[i], s[i], E[i] = preproc(R_NL_TYPE, x[i], E[i])
segIdx[i] = findSeg(x[i], R_SEG[N]) // N is segment group ID
If (segIdx[i] is valid)
{ 
tmp = alg_round_shift_right((A[segIdx[i]] * x[i]), n) + B[segIdx[i]];
Vd[i] = postproc(R_NL_TYPE, tmp)
}
N =(N+1) mod K; //K is the max segments group number
----

